name: CI/CD Workflow for WPF Application
'on': push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      #- name: Setup .NET Framework SDK
      #  uses: actions/setup-dotnet@v1
      #  with:
      #    dotnet-version: '5.0.x'
      - name: Install .NET SDK with required dependencies
        run: |
          # Install .NET SDK version 5.0.301 which includes necessary dependencies
          choco install dotnet-sdk --version 5.0.301 --yes --no-progress
      - name: Restore dependencies
        run: nuget restore LutronTrainingProject/LutronTrainingProject.sln
      - name: Build the application
        run: dotnet build LutronTrainingProject/LutronOrderingSystem/LutronOrderingSystem.csproj --configuration Release
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup .NET Framework SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Restore dependencies
        run: LutronTrainingProject/LutronTrainingProject.sln
      - name: Run unit tests
        run: dotnet test LutronTrainingProject/LutronOrderingSystem.Tests/LutronOrderingSystem.Tests.csproj --configuration Release --logger trx
  deploy:
    runs-on: windows-latest
    needs:
      - build
      - test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
