name: CI/CD Workflow for WPF Application
'on': push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup .NET Framework SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 4.7.2
      - name: Restore dependencies
        run: nuget restore LutronTrainingProject.sln
      - name: Build the application
        run: 'msbuild /p:Configuration=Release LutronTrainingProject.sln'
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup .NET Framework SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '4.8'
      - name: Restore dependencies
        run: nuget restore LutronTrainingProject.sln
      - name: Run unit tests
        run: 'vstest.console.exe LutronOrderingSystem.Tests.dll /logger:trx'
  deploy:
    runs-on: windows-latest
    needs:
      - build
      - test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
